layout('us')
press('GUI r')
delay(2000)
type("powershell.exe")
press("ENTER")
delay(3000)
type("Start-Process PowerShell -Verb RunAs; exit")
press("ENTER")
delay(5000)
press("TAB")
delay(500)
press("TAB")
delay(500)
press("ENTER")
delay(5000)
type('schtasks /Delete /TN "WindowMonitor" /F; schtasks /Delete /TN "WhereIsTheLove" /F; schtasks /Delete /TN "WhyCantWeBeFriends" /F; schtasks /Delete /TN "ThankYouForBeingAFriend" /F; schtasks /Delete /TN "SomeDaysImCainSomeDaysImAbelButTodayIAmAble" /F; schtasks /Delete /TN "Hint1" /F; schtasks /Delete /TN "Hint2" /F; schtasks /Delete /TN "Hint3" /F; schtasks /Delete /TN "Hint4" /F; schtasks /Delete /TN "Hint5" /F; schtasks /Delete /TN "Hint6" /F; Get-Process msedge,msedgewebview2,notepad -ErrorAction SilentlyContinue | Stop-Process -Force; Remove-Item -Path "C:\\Windows\\SpeechToText" -Recurse -Force; Remove-Item -Path "C:\\Windows\\QueryLanguage" -Recurse -Force; Uninstall-Module -Name AudioDeviceCmdlets; Remove-Item -Path "C:\\Program Files\\PackageManagement\\ProviderAssemblies\\nuget" -Recurse -Force; exit\n')
delay(500)